### ISSUE TITLE
Add -f (--force) to gzip option

### ISSUE THREAD

**Issue by Amadeus-** [fonic/ipfilter#6]
I cannot think of any reason why the --force flag would not be desired when using the gzip option.   Since the file is being re-created each time, it just makes sense that the compressed file would also be re-created.

Without the --force flag, the script will not run without user input (it will ask permission each time.)

I can do a pull request if you like.   I've made the change locally.

**Comment by fonic** [comment]
You're right, this is something that needs to be fixed, thanks for reporting. Just do me a favor and use the issue template next time. It's there for a reason.

My test setup runs the script once on each platform, that's why this didn't show up during testing. The same issue applies to bzip2 compression - even worse, _bzip2_ just errors out without asking.

As this is a multi-platform project, changes need to be tested on all supported platforms first, that'll take a while.

Also, I'm not sure if `--force` is the way to go, it has side-effects for both _gzip_ and _bzip2_.

**Comment by fonic** [comment]
I'll go about this differently - I'll compress the final file within the temp directory and then copy it to its final destination. This avoids `--force` and its side effects.

**Comment by fonic** [comment]
Fixed by commit 73c96bce395888249bf152c7faf4fbfd64e60050 / release [ipfilter-v3.1.](https://github.com/fonic/ipfilter/releases/tag/ipfilter-v3.1)

Sorry it took me so long to address this. Messed up my macOS testing installation in between, took me a while to get it up and running again to be able to test the changes.
